#!/bin/sh
set -eu

export HOME=/home/pn

NIX_DIR=$(cat /run/flake-docker/nix-dir)
export PATH="$NIX_DIR:$PATH"

cd /workspace

if [ -n "${SSH_ORIGINAL_COMMAND:-}" ]; then
  exec nix develop /env --command sh -lc "$SSH_ORIGINAL_COMMAND"
fi

exec nix develop /env --command sh
